# -*- coding: utf-8 -*-
# This file was generated by swagger2tapioca:
# https://gist.github.com/martelogan/86aa7efd83916d6d77bfca01d9c08b1b

RESOURCE_MAPPING = {
    "bourreaux": {
        "docs": "https://portal.cbrain.mcgill.ca/swagger#!/Bourreau", 
        "resource": "bourreaux/{id}"
    }, 
    "data_providers": {
        "docs": "https://portal.cbrain.mcgill.ca/swagger#!/DataProviders", 
        "resource": "data_providers/{id}"
    }, 
    "data_providers_browse": {
        "docs": "https://portal.cbrain.mcgill.ca/swagger#!/DataProviders", 
        "resource": "data_providers/{id}/browse"
    }, 
    "data_providers_delete": {
        "docs": "https://portal.cbrain.mcgill.ca/swagger#!/DataProviders", 
        "resource": "data_providers/{id}/delete"
    }, 
    "data_providers_is-alive": {
        "docs": "https://portal.cbrain.mcgill.ca/swagger#!/DataProviders", 
        "resource": "data_providers/{id}/is_alive"
    }, 
    "data_providers_register": {
        "docs": "https://portal.cbrain.mcgill.ca/swagger#!/DataProviders", 
        "resource": "data_providers/{id}/register"
    }, 
    "data_providers_unregister": {
        "docs": "https://portal.cbrain.mcgill.ca/swagger#!/DataProviders", 
        "resource": "data_providers/{id}/unregister"
    }, 
    "groups": {
        "docs": "https://portal.cbrain.mcgill.ca/swagger#!/Groups", 
        "resource": "groups/{id}"
    }, 
    "groups_switch": {
        "docs": "https://portal.cbrain.mcgill.ca/swagger#!/Groups", 
        "resource": "groups/switch"
    }, 
    "session": {
        "docs": "https://portal.cbrain.mcgill.ca/swagger#!/Sessions", 
        "resource": "session"
    }, 
    "session_new": {
        "docs": "https://portal.cbrain.mcgill.ca/swagger#!/Sessions", 
        "resource": "session/new"
    }, 
    "tags": {
        "docs": "https://portal.cbrain.mcgill.ca/swagger#!/Tags", 
        "resource": "tags/{id}"
    }, 
    "tasks": {
        "docs": "https://portal.cbrain.mcgill.ca/swagger#!/Tasks", 
        "resource": "tasks/{id}"
    }, 
    "tool_configs": {
        "docs": "https://portal.cbrain.mcgill.ca/swagger#!/ToolConfigs", 
        "resource": "tool_configs/{id}"
    }, 
    "tools": {
        "docs": "https://portal.cbrain.mcgill.ca/swagger#!/Tools", 
        "resource": "tools"
    }, 
    "userfiles": {
        "docs": "https://portal.cbrain.mcgill.ca/swagger#!/Userfiles", 
        "resource": "userfiles/{id}"
    }, 
    "userfiles_change-provider": {
        "docs": "https://portal.cbrain.mcgill.ca/swagger#!/Userfiles", 
        "resource": "userfiles/change_provider"
    }, 
    "userfiles_compress": {
        "docs": "https://portal.cbrain.mcgill.ca/swagger#!/Userfiles", 
        "resource": "userfiles/compress"
    }, 
    "userfiles_content": {
        "docs": "https://portal.cbrain.mcgill.ca/swagger#!/Userfiles", 
        "resource": "userfiles/{id}/content"
    }, 
    "userfiles_delete-files": {
        "docs": "https://portal.cbrain.mcgill.ca/swagger#!/Userfiles", 
        "resource": "userfiles/delete_files"
    }, 
    "userfiles_download": {
        "docs": "https://portal.cbrain.mcgill.ca/swagger#!/Userfiles", 
        "resource": "userfiles/download"
    }, 
    "userfiles_sync-multiple": {
        "docs": "https://portal.cbrain.mcgill.ca/swagger#!/Userfiles", 
        "resource": "userfiles/sync_multiple"
    }, 
    "userfiles_uncompress": {
        "docs": "https://portal.cbrain.mcgill.ca/swagger#!/Userfiles", 
        "resource": "userfiles/uncompress"
    }, 
    "users": {
        "docs": "https://portal.cbrain.mcgill.ca/swagger#!/Users", 
        "resource": "users/{id}"
    }
}
